name: Develop Workflow

on:
  push:
    branches: ['!release/**']
  pull_request:
    branches: [ 'develop', '!release/**' ]
    types: [ closed ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Contains Release: ${{ !contains(github.head_ref, 'release') }}"
          echo "Matches Develop: ${{ github.ref == 'refs/heads/develop' }}"
  build:
    name: Develop Workflow Ran
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !contains(github.head_ref, 'release')
    steps:
      - run: |
          echo Develop Workflow Ran