name: Stable Workflow

on:
  push:
    branches: ['release/**']
  pull_request:
    branches: [ 'develop' ]
    types: [ closed ]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Contains Release: ${{ !contains(github.head_ref, 'release') }}"
          echo "Matches Develop: ${{ github.ref == 'refs/heads/develop' }}"

  if_merged:
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
  build:
    name: Release Workflow Ran
    if: github.event.pull_request.merged == true && contains(github.head_ref, 'release')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Release Workflow Ran d
