name: Stable Workflow

on:
  push:
    branches: ['release/**']
  pull_request:
    branches: [ 'develop' ]
    types: [ closed ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
  build:
    name: Release Workflow Ran
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Release Workflow Ran
